import { useEffect, useState } from 'react';
import type { StageRecord } from '../types';

/**
 * Demo-facing names for the engine's stage ids.
 *
 * The ORDER comes from the server, never from this map, and Figma is extracted
 * before the website. That looks backwards and is not: a Figma frame is
 * fixed-width, and that width becomes the browser viewport, so M2 must precede
 * M1 (config.js applyFrameWidth). Do not re-sort these to read more naturally.
 */
const UI_LABEL: Record<string, string> = {
  M2: 'Extracting Figma',
  M4: 'Normalizing design',
  M1: 'Extracting Website',
  M3: 'Normalizing website',
  DET: 'Determinism check',
  P5: 'Pruning',
  P6: 'Spacing derivation',
  S1: 'Section Detection',
  S2: 'Matching',
  S3: 'Comparison',
  S4: 'Findings',
  S5: 'Report Generation',
};

/**
 * Stages worth explaining while they run.
 *
 * Measured: M1 takes 14-52s, DET adds about the same again, and S5 has run as
 * long as 92s. Everything else finishes in under 350ms. A silent spinner at S5
 * - the very last stage, at the end of a demo - is the worst place to leave a
 * viewer guessing, so name what it is waiting for.
 */
const SLOW: Record<string, string> = {
  M1: 'Loading the page and measuring every element',
  DET: 'Extracting a second time to prove the measurements are stable',
  S5: 'Writing the report — the summary is generated by a language model and can take up to a minute',
};

/** Which of a stage's info fields are worth showing a non-technical viewer. */
const INTERESTING = new Set([
  'nodes', 'width', 'frame', 'scrollHeight', 'findings', 'figma', 'web',
  'figmaSections', 'webSections', 'matched', 'missingInWeb', 'extraInWeb',
  'meanConfidence', 'critical', 'high', 'medium', 'low', 'identical', 'stale',
]);

function summarise(info: StageRecord['info']): string | null {
  if (!info) return null;
  const parts = Object.entries(info)
    .filter(([k, v]) => INTERESTING.has(k) && v !== null && v !== undefined && v !== false)
    .map(([k, v]) => `${k} ${v}`);
  return parts.length ? parts.join(' · ') : null;
}

const Elapsed = ({ since }: { since: number }) => {
  const [, tick] = useState(0);
  useEffect(() => {
    const t = setInterval(() => tick((n) => n + 1), 500);
    return () => clearInterval(t);
  }, []);
  return <span className="tabular-nums">{((Date.now() - since) / 1000).toFixed(0)}s</span>;
};

const Spinner = () => (
  <svg className="h-4 w-4 animate-spin text-indigo-600" viewBox="0 0 16 16" fill="none" aria-hidden>
    <circle cx="8" cy="8" r="6.5" stroke="currentColor" strokeOpacity="0.25" strokeWidth="2.5" />
    <path d="M8 1.5A6.5 6.5 0 0 1 14.5 8" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" />
  </svg>
);

function StageIcon({ status }: { status: StageRecord['status'] }) {
  if (status === 'running') return <Spinner />;
  if (status === 'ok')
    return (
      <svg className="h-4 w-4 text-emerald-600" viewBox="0 0 16 16" fill="none" aria-hidden>
        <path d="M3.5 8.5l3 3 6-7" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" />
      </svg>
    );
  if (status === 'failed')
    return (
      <svg className="h-4 w-4 text-rose-600" viewBox="0 0 16 16" fill="none" aria-hidden>
        <path d="M4.5 4.5l7 7m0-7l-7 7" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" />
      </svg>
    );
  return <span className="block h-1.5 w-1.5 rounded-full bg-slate-300" />;
}

interface Props {
  stages: StageRecord[];
  startedAt: number;
  retryNotice: string | null;
}

export function ProgressPanel({ stages, startedAt, retryNotice }: Props) {
  const [runningSince, setRunningSince] = useState<Record<string, number>>({});

  useEffect(() => {
    const now = Date.now();
    setRunningSince((prev) => {
      const next = { ...prev };
      for (const s of stages) {
        if (s.status === 'running' && !next[s.id]) next[s.id] = now;
        if (s.status !== 'running' && next[s.id]) delete next[s.id];
      }
      return next;
    });
  }, [stages]);

  const completed = stages.filter((s) => s.status === 'ok').length;

  return (
    <div className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm">
      <div className="mb-5 flex items-baseline justify-between">
        <h2 className="text-lg font-semibold text-slate-900">Running audit</h2>
        <span className="text-sm tabular-nums text-slate-500">
          {completed} of {stages.length} · <Elapsed since={startedAt} />
        </span>
      </div>

      {retryNotice && (
        <div className="mb-5 rounded-lg border border-amber-200 bg-amber-50 p-3.5 text-sm text-amber-900">
          {retryNotice}
        </div>
      )}

      {/*
        Deliberately not a percentage bar. Nine of twelve stages finish in under
        350ms, so a stage-count bar jumps to ~85% and then sits still for over a
        minute, which reads as a hang.
      */}
      <ol className="space-y-1">
        {stages.map((stage) => {
          const label = UI_LABEL[stage.id] ?? stage.label;
          const info = summarise(stage.info);
          const isRunning = stage.status === 'running';
          return (
            <li
              key={stage.id}
              className={[
                'flex items-start gap-3 rounded-lg px-3 py-2.5 transition-colors',
                isRunning ? 'bg-indigo-50/70' : '',
                stage.status === 'failed' ? 'bg-rose-50' : '',
              ].join(' ')}
            >
              <span className="mt-0.5 flex h-4 w-4 shrink-0 items-center justify-center">
                <StageIcon status={stage.status} />
              </span>

              <span className="min-w-0 flex-1">
                <span
                  className={[
                    'block text-[15px]',
                    stage.status === 'pending' ? 'text-slate-400' : 'text-slate-800',
                    isRunning ? 'font-medium text-indigo-900' : '',
                  ].join(' ')}
                >
                  {label}
                </span>

                {isRunning && SLOW[stage.id] && (
                  <span className="mt-0.5 block text-sm text-indigo-700/80">{SLOW[stage.id]}</span>
                )}
                {info && stage.status === 'ok' && (
                  <span className="mt-0.5 block font-mono text-xs text-slate-400">{info}</span>
                )}
                {stage.status === 'failed' && stage.message && (
                  <span className="mt-0.5 block text-sm text-rose-800">{stage.message}</span>
                )}
              </span>

              <span className="shrink-0 pt-0.5 text-xs tabular-nums text-slate-400">
                {isRunning && runningSince[stage.id] ? (
                  <Elapsed since={runningSince[stage.id]} />
                ) : stage.status === 'ok' && stage.ms !== null ? (
                  stage.ms >= 1000 ? `${(stage.ms / 1000).toFixed(1)}s` : `${stage.ms}ms`
                ) : null}
              </span>
            </li>
          );
        })}
      </ol>
    </div>
  );
}
